In [ ]:
##BackPropagation

import tensorflow as tf
import numpy as np


x_data = np.array([[0.1, 0.2]],dtype = np.float32)
y_data = np.array([[0.4, 0.6]],dtype = np.float32)

# almost fit
# w1 = 0.5794435
# w2 = 0.22913748
# w3 = 0.6877012
# w4 = 0.3364097

# w5 = 0.41938215
# w6 = 0.36839402
# w7 = 0.66790843
# w8 = 0.5661241

# w9 = -0.17201313
# w10 = 0.36238366
# w11 = -0.08488223
# w12 = 0.3664124

w1 = 1
w2 = 0
w3 = 1
w4 = 0

w5 = 0
w6 = 0
w7 = 1
w8 = 1

w9 = 0
w10 = 0
w11 = 0
w12 = 0


W1 = tf.Variable(tf.constant([[w1, w2], [w3, w4]], dtype = tf.float32))
W2 = tf.Variable(tf.constant([[w5, w6], [w7, w8]], dtype = tf.float32))
W3 = tf.Variable(tf.constant([[w9, w10], [w11, w12]], dtype = tf.float32))


learning_rate = 0.1

cost_val = []


def logisticRegression():
  with tf.GradientTape() as tape:
    t_layer1 = tf.matmul(x_data, W1)
    z_layer1 = tf.sigmoid(t_layer1)

    t_layer2 = tf.matmul(z_layer1, W2)
    z_layer2 = tf.sigmoid(t_layer2)

    t_layer3 = tf.matmul(z_layer2, W3)
    z_layer3 = tf.sigmoid(t_layer3)

    error =  tf.reduce_sum(tf.square(y_data - z_layer3))

    gradients = tape.gradient(error,[W3, W2, W1])
    tf.optimizers.SGD(learning_rate).apply_gradients(zip(gradients,[W3, W2, W1]))

for step in range(21):
  logisticRegression()
  t_layer1 = tf.matmul(x_data, W1)
  z_layer1 = tf.sigmoid(t_layer1)

  t_layer2 = tf.matmul(z_layer1, W2)
  z_layer2 = tf.sigmoid(t_layer2)

  t_layer3 = tf.matmul(z_layer2, W3)
  z_layer3 = tf.sigmoid(t_layer3)

  error =  tf.reduce_sum(tf.square(y_data - z_layer3))


print("Step : " ,step,
        "\n First Layer = \n", W1.numpy(),
        "\n Second Layer = \n", W2.numpy(),
        "\n OutPut Layer = \n", W3.numpy(),
        "\n error = ", error.numpy())

Step :  20 
 First Layer = 
 [[1.0000000e+00 6.3385924e-05]
 [1.0000000e+00 1.2677185e-04]] 
 Second Layer = 
 [[7.2801526e-04 7.2801526e-04]
 [1.0006334e+00 1.0006334e+00]] 
 OutPut Layer = 
 [[-0.05938062  0.05938064]
 [-0.05938062  0.05938064]] 
 error =  0.013291746


In [ ]:
##BackPropagation

import tensorflow as tf
import numpy as np


x_data = np.array([[0.1, 0.2]],dtype = np.float32)
y_data = np.array([[0.4, 0.6]],dtype = np.float32)

w1 = 0.3
w2 = 0.25
w3 = 0.4
w4 = 0.35

w5 = 0.45
w6 = 0.4
w7 = 0.7
w8 = 0.6

W1 = tf.Variable(tf.constant([[w1, w2], [w3, w4]], dtype = tf.float32))
W2 = tf.Variable(tf.constant([[w5, w6], [w7, w8]], dtype = tf.float32))
#W3 = tf.Variable(tf.constant([[w9, w10], [w11, w12]], dtype = tf.float32))

learning_rate = 0.5

cost_val = []


def logisticRegression():
  with tf.GradientTape() as tape:
    t_layer1 = tf.matmul(x_data, W1)
    z_layer1 = tf.sigmoid(t_layer1)

    t_layer2 = tf.matmul(z_layer1, W2)
    z_layer2 = tf.sigmoid(t_layer2)

    error =  tf.reduce_sum(tf.square(y_data - z_layer2))

    gradients = tape.gradient(error,[W2, W1])
    tf.optimizers.SGD(learning_rate).apply_gradients(zip(gradients,[W2, W1]))

#for step in range(21):
  logisticRegression()
  t_layer1 = tf.matmul(x_data, W1)
  z_layer1 = tf.sigmoid(t_layer1)

  t_layer2 = tf.matmul(z_layer1, W2)
  z_layer2 = tf.sigmoid(t_layer2)

  error =  tf.reduce_sum(tf.square(y_data - z_layer2))


print("Step : " ,step,
        "\n First Layer = \n", W1.numpy(),
        "\n Second Layer = \n", W2.numpy(),
      "\n t_layer2 Layer = \n", t_layer2.numpy(),
      "\n z_layer2 Layer = \n", z_layer2.numpy(),
        "\n error = ", error.numpy())

Step :  20 
 First Layer = 
 [[0.3  0.25]
 [0.4  0.35]] 
 Second Layer = 
 [[0.45 0.4 ]
 [0.7  0.6 ]] 
 t_layer2 Layer = 
 [[0.09423418 0.46673334]] 
 z_layer2 Layer = 
 [[0.52354115 0.61461025]] 
 error =  0.015475874
